runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /styles
  static_dir: styles

- url: /pictures
  static_dir: pictures

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
